services:
  django:
    image: django
    container_name: django
    build:
      context: ./back
    volumes:
      - ./back/:/usr/src/app
    ports:
      - "8000:8000"
    env_file: ./back/.env
    restart: always
    networks:
      - pong
  
  db_postgres:
    image: postgres
    container_name: postgres
    build:
      context: ./database
    ports:
      - "5432:5432"
    env_file: ./database/.env
    restart: always
    networks:
      - pong
  
  react:
    image: react
    container_name: react
    build:
      context: ./front
    ports:
      - "5173:5173"
    volumes:
      - ./front/frontend/:/app
    env_file: ./front/frontend/.env
    networks:
      - pong

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - pong

  redis:
    image: redis
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - pong
    
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    depends_on:
      - django
    ports:
      - 9443:443
    volumes:
      - ./front/frontend/dist/:/etc/front/frontend/dist/
    networks:
      - pong

networks:
  pong:
    driver: bridge
