# Generated by Django 5.1.1 on 2025-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangman',
            name='skin',
            field=models.URLField(default='Normal'),
        ),
    ]
