# Generated by Django 5.1.3 on 2024-11-13 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_sec_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='sec_id',
        ),
    ]
