# Generated by Django 5.1.1 on 2025-03-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_usersession_blockeduser_friend'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_map_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_paddle_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='default_points_index',
            field=models.IntegerField(default=0),
        ),
    ]
