# Generated by Django 5.1.1 on 2025-03-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_default_map_index_user_default_paddle_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_in_a_game',
            field=models.BooleanField(default=False),
        ),
    ]
