# Generated by Django 5.1.1 on 2025-03-03 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_match_longest_exchange_match_shortest_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.CharField(),
        ),
    ]
