# Generated by Django 5.1.1 on 2025-03-05 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_match_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourney',
            name='user1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='user2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='user3',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user3', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='user4',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user4', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='user5',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user5', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='user6',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user6', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='user7',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user7', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tourney',
            name='user8',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user8', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
