# Generated by Django 5.1.1 on 2025-03-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_tourney_user1_tourney_user2_tourney_user3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourney',
            name='user1',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user3',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user4',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user5',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user6',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user7',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tourney',
            name='user8',
            field=models.BigIntegerField(default=0),
        ),
    ]
