# Generated by Django 5.1.1 on 2025-03-06 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_tourney_user1_alter_tourney_user2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourney',
            name='name1',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='name2',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='name3',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='name4',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='name5',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='name6',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='name7',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='name8',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user2',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user3',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user4',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user5',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user6',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user7',
        ),
        migrations.RemoveField(
            model_name='tourney',
            name='user8',
        ),
        migrations.CreateModel(
            name='TourneyPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('profile_pic', models.URLField(default='https://wallpapers-clan.com/wp-content/uploads/2022/08/default-pfp-16.jpg')),
                ('tourney', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.tourney')),
            ],
        ),
    ]
