# Generated by Django 5.1.1 on 2025-03-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_remove_tourney_name1_remove_tourney_name2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourneyplayer',
            name='tourney',
            field=models.CharField(),
        ),
    ]
