# Generated by Django 5.1.1 on 2025-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_tourneyplayer_tourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourneyplayer',
            name='isUser',
            field=models.BooleanField(default=False),
        ),
    ]
