# Generated by Django 5.1.1 on 2025-03-07 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_tourneyplayer_isuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourneyplayer',
            name='profile_pic',
        ),
    ]
