# Generated by Django 5.1.1 on 2025-03-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_remove_tourneyplayer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='design_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='map_index',
            field=models.IntegerField(default=0),
        ),
    ]
