# Generated by Django 5.1.1 on 2025-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_tourney',
            field=models.BooleanField(default=False),
        ),
    ]
