# Generated by Django 5.1.1 on 2025-03-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_match_is_tourney'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='opponent',
            field=models.CharField(default='null'),
        ),
    ]
