# Generated by Django 5.1.1 on 2025-03-12 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_match_opponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hangman_score',
            field=models.BigIntegerField(default=0),
        ),
    ]
