# Generated by Django 5.1.1 on 2025-03-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0036_user_hangman_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField()),
                ('finded', models.BooleanField()),
                ('date', models.CharField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='hangman_lose_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hangman_win_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
