# Generated by Django 5.1.1 on 2025-03-13 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0037_hangman_user_hangman_lose_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangman',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
