# Generated by Django 5.1.1 on 2025-03-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_hangman_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hangman',
            name='finded',
            field=models.BooleanField(default=False),
        ),
    ]
