# Generated by Django 5.1.1 on 2025-03-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_hangman_finded'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hangman_find_letter',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='hangman_miss_letter',
            field=models.BigIntegerField(default=0),
        ),
    ]
