# Generated by Django 5.1.1 on 2025-03-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_alter_hangman_finded'),
    ]

    operations = [
        migrations.AddField(
            model_name='hangman',
            name='skin',
            field=models.CharField(default='Normal'),
        ),
        migrations.AddField(
            model_name='hangman',
            name='word_group',
            field=models.CharField(default='Normal'),
        ),
    ]
